= Živa
Syntax sugar for live coding in supercollider.
:toc:

== Quick Start
[source,sclang]
Ziva.boot;
~lola s: \tri >>>.1 1;

=== Explanation

`Ziva.boot` boots the server, starting the sound engine, initializing MIDI and loading default synth sounds.

The second line initializes an instrument named `~lola` which plays a synth with a variable triangle wave on the first channel of the mixer:

- `~lola` is the name of the instrument. It can be anything, but has to be lead by a `~`.
- `s:` is the method that sets the `sound` that the instrument will play.
- `\tri` is the sound name. See <<Ziva.sounds>>
- `>>>.1 1` sends this instrument's output to the mixer. The first number -- after the dot `.` --  is the `channel number`. The second is the `gain`.

== Syntax basics
There are two types of instructions: *system interaction* and *sound creation and managment*.

All the functions for the system interaction start with `Ziva.`. See <<System Interaction>> below for details on each one.

The syntax for creating and playing instruments can be devided into two parts: _defining_ the instrument sound and _playing_ it.

In any case, the line starts with the *name* of the instrument. It can be anything, but it *MUST* start with a `~` (tilde).

.Example
[source,sclang]
~lola

=== Defining an instrument

To define an instrument, its name is followed by a combination of methods.

.Syntax
[source,sclang]
<INSTRUMENT> <METHOD_1>: <VALUE_1> ... <METHOD_N>: <VALUE_N>

Any number of methods can be chained in any order, except for `s:`, which *ALLWAYS MUST* follow the sound name.

In the example below, an instrument named `~lola` is playing a variable triangle wave synth, with a `width` of 0.6, an amplitude of 0.8, and an ADSR envelope with it's attack set to 0.1, the sustain all the way down to 0, a decay of 0.8 and the default release -- non specified methods will use the sound defaults.

.Example
[source,sclang]
~lola s: \tri width: 0.6 amp: 0.8 atk: 0.1 sus: 0 dec: 0.8

See <<Sound>> for a full list of available methods and descriptions.

=== Playing an instrument

To play the instrument, its output needs to be _plugged_ to a mixer channel using the `>>>` operator.

.Syntax
[source,sclang]
<INSTRUMENT> >>>.<CHANNEL> <GAIN>

Note the `.` (dot) between the `>>>` operator and the `<CHANNEL>` number.

The example below sends the output of `~lola` to channel #2 of the mixer with a gain of `0.5`
[source,sclang]
~lola >>>.2 0.5

This operator can be put at the end of any line that starts with an instrument name, and it will route that instrument to the given mixer channel.

The instrument in the example above can be defined and played in one single line.

.Example
[source,sclang]
~lola s: \tri width: 0.6 amp: 0.8 atk: 0.1 sus: 0 dec: 0.8 >>>.2 0.5

== Sound

=== fxN
Set an effect on the signal chain of an instrument or the mixer.

Then `N` sets the order of the effects, so the dry signal goes into `fx1`, the output of `fx1` goes into `fx2` and so on.

See <<wetN>>.

.Argument
See <<Effects>>.

CAUTION:  to completely remove an effect from the signal chain, it *MUST* be explicitly *set it to `nil`*. +
          For example: `~lola fx1: nil`


=== wetN
Set the effect's signal mix between dry (`0`) and wet (`1`).

.Example
[source,sclang]
~lola fx1: delay(0.3, 1) wet1: 0.8

=== >>>.channel gain
Send a sound output to a mixer channel with a set `gain`.

.Argument
- `channel` _int_ - number of the channels in the mixer.
- `gain` _float_ - output gain.



== Effects
=== delay(time, fadetime)
=== fbdelay(time, feedback)
=== swdelay(time, feedback)
=== reverb(mix, size, damp)
=== limit(amp)

== System Interaction
Živa offers a collection of methods to interact with the server and the livecoding environment.

=== Ziva.boot(inputChannels, outputChannels, server)
.Arguments
- `inputChannels` _int_ - number of input channels. Defaults to `2`
- `outputChannels` _int_ - number of output channels. Defaults to `2`.
- `server` _Server_ - SuperCollider server instance. Defaults to `Server.default`.
.Usage
[source,sclang]
Ziva.boot;

with optional arguments:
[source,sclang]
Ziva.boot(outputChannels:2)

with ordered arguments, 2 inputs and 2 outputs:
[source,sclang]
Ziva.boot(2, 2)

=== Ziva.sounds
List all available sounds, synths and samples.

Samples will display the number of files in the corresponding directories.

=== Ziva.samples(path)
Load samples from the given `path`.
.Arguments
- `path` _String_ - absolute path to the parent folder containing sample directories.

.Usage
The path has to point to a parent directory (folder) containing subdirectories with audio files. The subdirecotries' names will be then used to identify samples by name.

Here's a structure example:

 ~/samples
   /kick
   /snare
   /ch
   /oh
   /clap
   /voices

Then the samples can be loaded with:

[source,sclang]
Ziva.samples("~/samples");
