#+title: Živa

Live coding with SuperCollider patterns made easy (hopefully).

A set of tools and syntax sugar for easy live coding with synthdef and sample patterns in SuperCollider.

Živa was developed in a residency at [[https://wiki.ljudmila.org/Research_residency:_Roger_Pibernat][Ljudmila]] (in Ljubljana, Slovenia) as part of the [[https://onthefly.space][On-the-fly project]].

Regular SuperCollider pattern and Ndef syntax can be used as parameters inside Živa functions.

/WARNING: This software is still under heavy development and might considerably change in future versions./

* Documentation

See [[./docs/Reference.md][Quick Reference Guide]].

* Requirements
** All OS

    - SuperCollider: https://github.com/supercollider/supercollider - tested with v3.12.2
    - sc3-plugins: https://github.com/supercollider/sc3-plugins/
    - optional, but recommended (for the Dirt-Samples library): SuperDirt quark: https://github.com/musikinformatik/SuperDirt

** Windows
  Windows users also need to install git: https://gitforwindows.org/

* Installation from SuperCollider
#+begin_src sclang
Quarks.install("https://github.com/loopier/ziva");
#+end_src

if you have already installed it before, and simply want to update:

#+begin_src sclang
Quarks.update("ziva");
#+end_src

* License
(C) 2022- Roger Pibernat

Živa is free software: you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation, either version 2 of the License, or (at your
option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this library.  If not, see <http://www.gnu.org/licenses/>.
